name: 柳溪斋

on:
  push:
    branches: [main, master]
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  blog:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2
      
      # 设置 Node.js 版本
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # 替换为你的本地 Node.js 版本

      # 缓存 Node.js 依赖
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # 安装 Hexo 所需的依赖
      - name: Install dependencies
        run: |
          npm install
          npm install hexo-butterfly-tag-plugins-plus --save
          echo "Dependencies installed successfully."

      # 安装 Hexo-cli
      - name: Install Hexo-cli
        run: |
          npm install -g hexo-cli --save
          echo "Hexo CLI installed successfully."

      # 编译博客文件
      - name: Build Blog
        run: |
          hexo clean
          hexo generate --debug
          echo "Blog build process completed."

      # 部署博客
      - name: Deploy Blog
        run: |
          git config --global user.name "Donis2"
          git config --global user.email "2561055937@qq.com"
          hexo deploy

      - run: echo "Deploy Successful!"
