name: 柳溪斋

on:
  push:
    branches: [main, master]
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  blog:
    timeout-minutes: 30  # 设置 30 分钟超时
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为构建环境

    steps:
      # 检出代码
      - uses: actions/checkout@v2
        name: Checkout code

      # 设置 Node.js 版本
      - uses: actions/setup-node@v2
        with:
          node-version: '16'  # 替换为你本地使用的 Node.js 版本

      # 缓存 Node.js 依赖
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # 安装 Hexo 依赖
      - name: Install dependencies
        run: |
          npm install
          npm install hexo-butterfly-tag-plugins-plus --save
          echo "Dependencies installed successfully."

      # 安装 Hexo-cli
      - name: Install Hexo-cli
        run: |
          npm install -g hexo-cli --save
          echo "Hexo CLI installed successfully."

      # 初始化子模块
      - name: Initialize submodules
        run: |
         git submodule sync
         git submodule update --init --recursive
         echo "Submodules initialized successfully."


      # 清理 .deploy_git 文件夹
      - name: Remove .deploy_git folder
        run: |
          rm -rf .deploy_git
          echo ".deploy_git folder cleared."

      # 编译博客
      - name: Build Blog
        run: |
          hexo clean
          hexo generate --debug  # 开启调试模式以便排查问题
          echo "Blog build process completed."

      # 部署博客
      - name: Deploy Blog
        run: |
          git config --global user.name "Donis2"
          git config --global user.email "2561055937@qq.com"
          hexo deploy --debug  # 开启部署的调试模式，帮助调试部署时的问题

      # 部署成功 
      - run: echo "Deploy Successful!"
